# Exported from Render on 2026-05-21T16:09:10Z
version: "1"
services:
- type: web
  name: n8n1
  runtime: image
  image:
    url: docker.io/library/nginx:latest
  plan: free
  envVars:
  - key: N8N_ENCRYPTION_KEY
    sync: false
  - key: WEBHOOK_URL
    sync: false
  - key: N8N_PROTOCOL
    sync: false
  - key: N8N_HOST
    sync: false
  region: oregon
  autoDeployTrigger: commit
